site_name: Lambda Science - cmeyer.fr
site_url: https://cmeyer.fr
site_author: Corentin Meyer
site_description: Lambda Science - Corentin Meyer's personal blog
theme:
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/lightbulb  
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/solid/microscope
  favicon: images/logo.svg
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - social
nav:
  - Home: index.md
  - Blog & TILs: blog/index.md
  - About Me: aboutme.md
markdown_extensions:
  - attr_list
  - admonition
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  analytics:
    provider: custom
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/corentinm_py
    - icon: material/email 
      link: mailto:lambdascience@tutanota.com
    - icon: simple/linkedin 
      link: https://www.linkedin.com/in/corentin-m-78056887/
    - icon: simple/github
      link: https://github.com/lambda-science