site_name: Lambda Science - cmeyer.fr
site_url: https://cmeyer.fr
site_author: Corentin Meyer
site_description: Lambda Science - Corentin Meyer's personal blog
extra_css:
  - stylesheets/extra.css
theme:
  font: 
    text: Inter
    code: Berkeley Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/lightbulb  
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/solid/microscope
  favicon: images/logo.svg
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
plugins:
  - search
  - social
  - tags
  - blog:
      post_date_format: medium
      post_url_format: "{slug}"
      archive_url_format: "{date}"
      archive: false
      categories: false
nav:
  - Home: index.md
  - Blog & TILs: blog/index.md
  - About Me: aboutme.md
markdown_extensions:
  - attr_list
  - admonition
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  generator: false
  analytics:
    provider: custom
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/corentinm_py
    - icon: material/email 
      link: mailto:contact@cmeyer.fr
    - icon: simple/linkedin 
      link: https://www.linkedin.com/in/corentin-meyer/
    - icon: simple/github
      link: https://github.com/lambda-science